import en from "./en";

const hi: Record<keyof typeof en, string> = {
  languageLabel: "भाषा बदलें", english: "English", hindi: "हिन्दी", primaryNavigation: "मुख्य नेविगेशन", homeAria: "योजनासेतु मुख्य पृष्ठ", logoAlt: "योजनासेतु — पात्रता से आवेदन तक", findScheme: "योजना खोजें", myJourney: "मेरी यात्रा", signIn: "साइन इन", signOut: "साइन आउट", signOutAria: "{{email}} को साइन आउट करें", footerBrand: "योजनासेतु — पात्रता से आवेदन तक", footerCopy: "यह केवल मार्गदर्शन और पात्रता सहायता के लिए है। अंतिम सत्यापन और आवेदन आधिकारिक सरकारी माध्यमों से होते हैं।",

  homeEyebrow: "पात्रता से आवेदन तक", homeTitle: "वह सहायता खोजें जो आपके लिए है।", homeDescription: "योजनाएँ खोजें, सेवा से मिले पात्रता परिणाम को समझें, अपने दस्तावेज़ तैयार करें और सुरक्षित रूप से आधिकारिक पोर्टल पर आगे बढ़ें।", findForMe: "मेरे लिए योजनाएँ खोजें", privacyNotice: "यहाँ आधार नंबर, ओटीपी, पासवर्ड या बैंक विवरण नहीं लिया जाता है।", heroImageAlt: "सहायता खोजने से आधिकारिक आवेदन तक नागरिक की यात्रा", clearJourney: "एक स्पष्ट यात्रा", journeyFlow: "खोजें → समझें → तैयार करें → आधिकारिक रूप से आवेदन करें", howItHelps: "योजनासेतु कैसे मदद करता है", discover: "खोजें", discoverDescription: "अपनी जानकारी या सामान्य भाषा में पूछे गए सवाल से शुरू करें।", understand: "समझें", understandDescription: "सेवा द्वारा लौटाई गई पात्रता की जानकारी पढ़ें।", prepare: "तैयार करें", prepareDescription: "जिन दस्तावेज़ों की ज़रूरत है, उनमें से तैयार दस्तावेज़ों को चिह्नित करें।", applyOfficially: "आधिकारिक रूप से आवेदन करें", applyOfficiallyDescription: "सरकारी पोर्टल पर सत्यापन और आवेदन पूरा करें।",

  profileBuilder: "आपकी जानकारी", basicDetails: "बुनियादी जानकारी", economicDetails: "आर्थिक जानकारी", educationOccupation: "शिक्षा और काम", reviewProfile: "अपनी जानकारी जाँचें", profileStep: "चरण {{current}} / {{total}}", profileStepAria: "चरण {{current}} / {{total}}", profileIntro: "हम केवल वही जानकारी पूछते हैं जो योजना की पात्रता जाँचने में उपयोगी हो। नतीजे देखने से पहले आप इस जानकारी को देख और बदल सकते हैं।", state: "राज्य", age: "उम्र", annualIncome: "परिवार की वार्षिक आय (₹)", category: "श्रेणी", occupation: "काम", education: "शिक्षा", chooseOption: "एक विकल्प चुनें", maharashtra: "महाराष्ट्र", karnataka: "कर्नाटक", uttarPradesh: "उत्तर प्रदेश", westBengal: "पश्चिम बंगाल", other: "अन्य", farmer: "किसान", student: "विद्यार्थी", salaried: "नौकरीपेशा", selfEmployed: "स्वरोज़गार", seekingWork: "काम की तलाश में", school: "स्कूल", diploma: "डिप्लोमा", undergraduate: "स्नातक", postgraduate: "स्नातकोत्तर", general: "सामान्य", obc: "ओबीसी", sc: "एससी", st: "एसटी", preferNotToSay: "नहीं बताना चाहते", completeFields: "आगे बढ़ने के लिए इस चरण के सभी फ़ील्ड भरें।", checkingSession: "आपका सत्र जाँचा जा रहा है…", signInToSave: "अपनी जानकारी सुरक्षित रूप से सहेजने के लिए साइन इन करें।", profileLoadError: "आपकी सहेजी हुई जानकारी नहीं खुल सकी। आप नीचे दी गई जानकारी के साथ आगे बढ़ सकते हैं।", profileSaveExpired: "आपका सत्र समाप्त हो गया है। कृपया फिर से साइन इन करें।", profileSaveError: "आपकी जानकारी सहेजी नहीं जा सकी। कृपया फिर से कोशिश करें।", back: "पीछे", continue: "आगे बढ़ें →", saving: "सहेजा जा रहा है…", submitProfile: "जानकारी जमा करें",

  personalizedResults: "आपके लिए नतीजे", completeProfileFirst: "पहले अपनी जानकारी पूरी करें।", profileRequiredDescription: "जानकारी होने पर सुझाव सेवा आपके लिए सही योजनाएँ दिखा सकती है। यह आपके ब्राउज़र में पात्रता का निर्णय नहीं लेती।", buildProfile: "मेरी जानकारी भरें →", schemesToExplore: "देखने योग्य योजनाएँ", resultsDescription: "रैंक और मेल की जानकारी सेवा से मिलती है। पूरी जाँच देखने के लिए योजना खोलें।", editProfile: "जानकारी बदलें", filterSchemes: "योजनाएँ छाँटें", catalogueFilterPlaceholder: "योजना सूची में छानें", filter: "छानें", loadingSchemeResults: "योजनाओं के नतीजे लोड हो रहे हैं…", recommendationsError: "सुझाव उपलब्ध नहीं हैं। आप फिर भी योजनाएँ देख सकते हैं।", catalogueError: "योजना सूची उपलब्ध नहीं है। कृपया फिर से कोशिश करें।", tryAgain: "फिर से कोशिश करें", noSchemesMatched: "इस छँटाई से कोई योजना नहीं मिली।", noSchemesMatchedDescription: "कुछ सामान्य शब्द आज़माएँ या सामान्य भाषा में खोजें।",

  reverseSchemeSearch: "ज़रूरत के आधार पर योजना खोजें", describeNeed: "बताइए, आपको किस सहायता की ज़रूरत है।", searchDescription: "जैसे “5 लाख का इलाज कार्ड”, “लड़कियों की छात्रवृत्ति” या “किसानों के लिए सालाना सहायता”। खोज की व्याख्या, भरोसे का स्तर और आगे के सवाल बैकएंड/एआई सेवा से आते हैं।", describeBenefitAria: "लाभ या योजना का विवरण दें", searchPlaceholder: "उदाहरण: मेरे परिवार के लिए इलाज सहायता", search: "खोजें", searching: "खोजा जा रहा है…", searchUnavailable: "खोज अभी उपलब्ध नहीं है। कृपया बाद में कोशिश करें।", semanticSearchPending: "सिमैंटिक खोज को सदस्य 3 जोड़ रहे हैं। आप अपनी जानकारी के आधार पर योजनाएँ देख सकते हैं।", lookingForMatches: "संभव योजनाओं की खोज हो रही है…", searchServiceGuidance: "खोज सेवा का मार्गदर्शन", chooseBestResult: "वह नतीजा चुनें जो आपकी ज़रूरत के सबसे करीब है।", noSearchMatches: "कोई संभावित योजना नहीं मिली। लाभ, राज्य या सहायता किसे चाहिए, यह लिखकर कोशिश करें।",

  loadingSchemeDetails: "योजना की जानकारी लोड हो रही है…", schemeUnavailable: "योजना उपलब्ध नहीं है।", schemeLoadError: "यह योजना लोड नहीं हो सकी। यह उपलब्ध न हो या इसकी जानकारी पुरानी हो सकती है।", backToSchemes: "← योजनाओं पर वापस जाएँ", schemeType: "{{type}} योजना · {{status}}", saved: "सहेजी गई ✓", saveScheme: "योजना सहेजें", explanationLabel: "योजनासेतु की व्याख्या:", explanationCopy: "यह पृष्ठ आपको योजना समझने में मदद करता है।", officialSource: "आधिकारिक स्रोत:", lastVerified: "अंतिम जाँच {{date}}।", verificationStatus: "सत्यापन स्थिति: सूची में इसे {{status}} बताया गया है।", benefits: "लाभ", targetUsers: "लक्षित लाभार्थी:", department: "विभाग:", documentsProgress: "दस्तावेज़ — {{ready}} / {{total}} ज़रूरी दस्तावेज़ तैयार", documentChecklistCopy: "केवल उन्हीं दस्तावेज़ों को चिह्नित करें जो आपके पास हैं। यह स्थानीय तैयारी सूची है, दस्तावेज़ सत्यापन नहीं।", required: "ज़रूरी", optional: "वैकल्पिक", documentSourceCopy: "यह आमतौर पर संबंधित अधिकृत कार्यालय या पोर्टल से जारी या प्राप्त होता है।", guidedTutorial: "आवेदन की चरण-दर-चरण सहायता", prepareOfficialApplication: "आधिकारिक आवेदन के लिए तैयार हों", officialPortalScreen: "आधिकारिक पोर्टल स्क्रीन का चित्र", officialPortal: "आधिकारिक पोर्टल", illustrativeScreen: "चरण की उदाहरण स्क्रीन", tutorialStep: "चरण {{current}} / {{total}}", helpfulNote: "सहायक बात:", warning: "सावधानी:", previous: "पिछला", next: "अगला", noTutorial: "इस योजना के लिए अभी कोई मार्गदर्शिका उपलब्ध नहीं है।", eligibilityResult: "आपकी पात्रता का परिणाम", completeProfileForEligibility: "बैकएंड से पात्रता परिणाम पाने के लिए अपनी जानकारी पूरी करें।", completeProfile: "जानकारी पूरी करें", serviceReturnedEligibility: "सेवा ने पात्रता का एक परिणाम लौटाया है।", pass: "पूरा", missing: "बाकी", fail: "पूरा नहीं", requiredValue: "ज़रूरी:", yourValue: "आपका विवरण:", addMissingDetails: "बाकी जानकारी जोड़ें",

  profileCompletion: "जानकारी पूरी होने की स्थिति", profileCompletionValue: "{{count}} / 6 जानकारी", recommendedSchemes: "सुझाई गई योजनाएँ", readyToExplore: "देखने के लिए तैयार", profileNeeded: "जानकारी चाहिए", viewResults: "नतीजे देखें", documentReadiness: "दस्तावेज़ों की तैयारी", trackedPerScheme: "हर योजना के लिए अलग", openSavedSchemes: "सहेजी योजनाएँ खोलें", savedSchemes: "सहेजी गई योजनाएँ", noSavedSchemes: "अभी कोई योजना सहेजी नहीं गई है। इस प्रारूप में सहेजी चीज़ें आपके डिवाइस पर रहती हैं।", recentActivity: "हाल की गतिविधि", recentActivityCopy: "जब बैकएंड में सहेजने का अनुबंध उपलब्ध होगा, तब हाल की खोज और जारी मार्गदर्शिका यहाँ दिखाई जाएगी। यह प्रारूप आवेदन जमा होने को ट्रैक करने का दावा नहीं करता।",

  viewDetails: "विवरण देखें", matchPercentage: "{{score}}% मेल", schemeFallbackTag: "योजना", eligible: "पात्र", potentiallyEligible: "संभावित रूप से पात्र", notEligible: "पात्र नहीं", moreInformationRequired: "अधिक जानकारी चाहिए",

  continueOfficialPortal: "आधिकारिक पोर्टल पर जाएँ", leavingYojanaSetu: "आप योजनासेतु से बाहर जा रहे हैं", handoffCopy: "अब आप {{name}} के आधिकारिक माध्यम पर जाएँगे। अंतिम सत्यापन और आवेदन वहीं होगा।", continueOfficially: "आधिकारिक रूप से आगे बढ़ें ↗", stayOnYojanaSetu: "योजनासेतु पर रहें",

  signInTitle: "साइन इन", createAccountTitle: "खाता बनाएँ", authCopy: "आपका सत्र Supabase Auth के माध्यम से सुरक्षित रूप से प्रबंधित होता है।", email: "ईमेल", password: "पासवर्ड", authError: "प्रमाणीकरण पूरा नहीं हो सका।", pleaseWait: "कृपया प्रतीक्षा करें…", createAccount: "खाता बनाएँ", useSignIn: "साइन इन करें", cancel: "रद्द करें",

  microphoneUse: "माइक्रोफ़ोन इस्तेमाल करें", microphoneStop: "माइक्रोफ़ोन बंद करें", microphoneDenied: "माइक्रोफ़ोन की अनुमति नहीं मिली", microphoneUnavailable: "माइक्रोफ़ोन उपलब्ध नहीं है", listening: "सुन रहा है", permissionDenied: "अनुमति नहीं मिली",

  pageNotFound: "पृष्ठ नहीं मिला", returnHome: "मुख्य पृष्ठ पर जाएँ", unexpectedError: "एक अनपेक्षित त्रुटि हुई है।", reloadPage: "पृष्ठ फिर से लोड करें",

  eligibleDescription: "दी गई जानकारी के आधार पर सेवा ने प्रारंभिक रूप से पात्र परिणाम लौटाया है। अंतिम निर्णय आधिकारिक विभाग लेता है।", needsDetails: "आपकी पात्रता की पुष्टि के लिए कुछ और जानकारी चाहिए।", missingInfoAria: "ज़रूरी जानकारी जो अभी बाकी है", answerMissingQuestions: "बाकी सवालों के जवाब दें →", notEligibleDescription: "दी गई जानकारी के आधार पर आप इस योजना की शर्तें पूरी नहीं करते हैं। अंतिम निर्णय आधिकारिक विभाग लेता है।", ineligibilityAria: "अपात्र होने के कारण",
};

export default hi;
